image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository
    - target/

build:
  stage: build
  tags: 
    - DOCKER
  script:
    - 'mvn $MAVEN_CLI_OPTS install'
    
deploy:
  stage: deploy
  tags: 
    - DOCKER
  script:
    - 'mvn $MAVEN_CLI_OPTS deploy'
  only:
    - wf92adaptations

  

